from pathlib import Path
import os
print(os.getcwd())
print(os.listdir("./mkdocs_pyscript"))
js_files = ['./mkdocs_pyscript/mini-coi.js', './mkdocs_pyscript/makeblocks.js']

for file in js_files:
    with open(file, "r") as f:
        contents = f.read()
        p = Path(file)
        varname = p.name.replace(".js", "").replace(" ", "").replace("-", "")
        with open(p.parent / (varname + ".py"), "w+") as out:
            out.write("# This file is generated by buildjs.py, do not modify!\n\n")
            out.write(f"{varname} = \"\"\"{contents}\"\"\"")

